server:
  port: 9090
  error:
    include-stacktrace: always

service:
  name: ftmanager

springfox:
  documentation:
    swagger:
      v2:
        path: /public/swagger.json

spring:
  application:
    name: ${service.name}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
  datasource:
    url: jdbc:postgresql://postgres:5432/${service.name}
    ##url: jdbc:postgresql://localhost:5442/${service.name}
    username: root
    password: 1525
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  flyway:
    locations: classpath:db/migration
    validate-on-migrate: true
    baseline-on-migrate: true
